### ISSUE TITLE
a question ,AttributeError

### ISSUE THREAD

**Issue by panpan0123** [Nobuho/191111_IFCandNeo4j#1]
Hello sir,how to solve  "AttributeError: 'str' object has no attribute 'get_attribute_names' "in line 21 of AllSameNode.py

**Comment by Nobuho** [comment]
I had a same problem when I used Python3.6 or later. This script works on Python3.5 only because IfcOpenShell can work on this version. Do you use Python3.5 ?

**Comment by panpan0123** [comment]
Yes,i do.And i try other function of IfcOpenshell using python3.5,it runs with no error.

**Comment by panpan0123** [comment]
my test function is ifcOpenshell.open()

**Comment by panpan0123** [comment]
i feel very puzzled

**Comment by panpan0123** [comment]
are there  some errors in this code
"
class IfcTypeDict(dict):
    def __missing__(self, key):
        value = self[key] = IfcOpenShell.create_entity(key).wrapped_data.get_attribute_names()
        return value
assert typeDict["IfcWall"] == (
    'GlobalId',
    'OwnerHistory',
    'Name',
    'Description',
    'ObjectType',
    'ObjectPlacement',
    'Representation',
    'Tag')

"

**Comment by Nobuho** [comment]
I tried myself again today. Ifcopenshell library was updated, so it didn't work. I modified codes and add some text in Readme. Now my codes works with Python3.8.0. Could you check it and try again?
